language: cpp
os:
  - osx

compiler:
  - clang

install:
  - brew install qt cmake python
  - pip3 install --user cpp-coveralls

script:
  - cd Receiver
  - ./build.sh debug

after_success:
  - coveralls -r .. --gcov-options '\-lp' -E ".*CMakeFiles.*"
