language: cpp
dist: bionic
os:
  - linux
sudo: required

compiler:
  - g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - cmake
      - cmake-data
      - lcov
      - ggcov

before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.14.0-bionic
  - sudo apt-get -qq update

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-9" CC="gcc-9"; fi
  - echo ${CC}
  - echo ${CXX}
  - ${CXX} --version
  - cmake --version
  - pip install --user cpp-coveralls
  - sudo apt-get install -qq qt514base qt514tools qt514svg qt514script
  - source /opt/qt514/bin/qt514-env.sh

script:
  - cd Receiver
  - ./build.sh debug

after_success:
  - coveralls -r .. --gcov-options '\-lp' -E ".*CMakeFiles.*"
